CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8 ;
USE `optica` ;
CREATE TABLE IF NOT EXISTS `optica`.`proveedor` (  `id_proveedor` INT(11) NOT NULL,  `nombre` VARCHAR(45) NULL,  `calle` VARCHAR(45) NOT NULL,  `numero` INT(11) NOT NULL,  `piso` INT(11) NOT NULL,  `puerta` VARCHAR(10) NOT NULL,  `ciudad` VARCHAR(45) NOT NULL,  `codigo_postal` INT(11) NOT NULL,  `pais` VARCHAR(45) NOT NULL,  `telefono` INT(11) NULL,  `fax` INT(11) NULL,  `NIF` VARCHAR(45) NULL,  PRIMARY KEY (`id_proveedor`));
CREATE TABLE IF NOT EXISTS `optica`.`productos` (  `id_productos` INT(11) NOT NULL,  `marca` VARCHAR(45) NULL,  `graduacion_derecho` INT(11) NULL,  `graduacion_izquierdo` INT(11) NULL,  `precio` DECIMAL(2) NULL,  `id_proveedor` INT(11) NULL,  `id_montura` INT(11) NULL,  PRIMARY KEY (`id_productos`),  INDEX `id_proveedor_idx` (`id_proveedor` ASC),  INDEX `id_montura_idx` (`id_montura` ASC),  CONSTRAINT `id_proveedor`    FOREIGN KEY (`id_proveedor`)    REFERENCES `optica`.`proveedor` (`id_proveedor`)    ON DELETE CASCADE    ON UPDATE CASCADE,  CONSTRAINT `id_montura`    FOREIGN KEY (`id_montura`)    REFERENCES `optica`.`tipo_montura` (`id_montura`)    ON DELETE CASCADE    ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS `optica`.`presentador` (  `id_presentador` INT(11) NOT NULL,  `nombre` VARCHAR(45) NULL,  PRIMARY KEY (`id_presentador`));
CREATE TABLE IF NOT EXISTS `optica`.`clientes` (  `id_clientes` INT(11) NOT NULL,  `codigo_postal` VARCHAR(45) NULL,  `telefono` INT(11) NULL,  `email` VARCHAR(45) NULL,  `fecha_registro` DATETIME NOT NULL,  `id_presentador` INT(11) NULL,  PRIMARY KEY (`id_clientes`),  INDEX `id_presentador_idx` (`id_presentador` ASC),  CONSTRAINT `id_presentador`    FOREIGN KEY (`id_presentador`)    REFERENCES `optica`.`presentador` (`id_presentador`)    ON DELETE NO ACTION    ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS `optica`.`empleados` (  `id_empleados` INT(11) NOT NULL,  `nombre` VARCHAR(45) NULL,  PRIMARY KEY (`id_empleados`));
CREATE TABLE IF NOT EXISTS `optica`.`ventas` (  `id_venta` INT(11) NOT NULL,  `fecha` VARCHAR(45) NULL,  `id_productos` INT(11) NULL,  `id_clientes` INT(11) NULL,  `id_empleados` INT(11) NULL,  PRIMARY KEY (`id_venta`),  INDEX `id_productos_idx` (`id_productos` ASC),  INDEX `id_empleados_idx` (`id_empleados` ASC),  INDEX `id_clientes_idx` (`id_clientes` ASC),  CONSTRAINT `id_productos`    FOREIGN KEY (`id_productos`)    REFERENCES `optica`.`productos` (`id_productos`)    ON DELETE NO ACTION    ON UPDATE NO ACTION,  CONSTRAINT `id_empleados`    FOREIGN KEY (`id_empleados`)    REFERENCES `optica`.`empleados` (`id_empleados`)    ON DELETE NO ACTION    ON UPDATE NO ACTION,  CONSTRAINT `id_clientes`    FOREIGN KEY (`id_clientes`)    REFERENCES `optica`.`clientes` (`id_clientes`)    ON DELETE NO ACTION    ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS `optica`.`tipo_montura` (  `id_montura` INT NOT NULL AUTO_INCREMENT,  `tipo` VARCHAR(45) NOT NULL,  `color` VARCHAR(45) NOT NULL,  PRIMARY KEY (`id_montura`));


